### ISSUE TITLE
Duplicate table numbers in HTML without section numbering

### ISSUE THREAD

**Issue by timtroendle** [tomduck/pandoc-tablenos#17] opened 2020-02-28 09:15 UTC
Without section numbering, table numbers in HTML restart in each section nevertheless.

Here is an example:
```
# First section

[table def here]

# Second section

[table def here]
```

This leads to both tables having number 1.

**Comment by timtroendle** [comment] 2020-02-28 09:19
The same issue and the same fix exists for fignos:

https://github.com/tomduck/pandoc-fignos/issues/76

**Comment by tomduck** [comment] 2020-07-30 12:08
Thank you for this report and sorry for the long wait.  The problem is now fixed in the `nextrelease` branch.  If the problem reappears after the next release, please feel welcome to re-open this issue.

Tom

**Closed as completed by tomduck** 2020-07-30 12:08 UTC
Labels: bug
